### ISSUE TITLE
New version checklist

### ISSUE THREAD

**Issue by bqpd** [convexopt/gpkit#332]
* [ ] Update MANIFEST
 * [ ] Update [release notes](https://github.com/convexopt/gpkit/releases)
 * [ ] Update Sphinx documentation for any new / changed syntax
 * [x] Rebuild Sphinx examples

**Comment by bqpd** [comment]
**Sphinx Documentation to be written**

  * [ ] dealing with infeasibility [0.3]
  * [ ] allow nonoptimal results from solver (+unit test) [0.3]
  * [ ] interactive widgets [0.4]

**Comment by bqpd** [comment]
**Sphinx Documentation to be written**

  * [ ] dealing with infeasibility [0.3]
  * [ ] allow nonoptimal results from solver (+unit test) [0.3]
  * [ ] interactive widgets [0.4]

**Comment by whoburg** [comment]
who checked off "Update version number"? I still see 0.1.1 in `docs/source/conf.py`.

**Comment by whoburg** [comment]
doh, it's in #328. my mistake.

**Comment by bqpd** [comment]
No worries! Gonna delete all these comments when I move the issue.

**Comment by whoburg** [comment]
MANIFEST updated in 7a9a930a7a3cc61b5b47909963d5dc8440c92e10, should we check it off?

**Comment by bqpd** [comment]
Nope, I was waiting for changes from #394
